# Generated by Django 4.2 on 2024-02-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attractions', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('status', models.BooleanField(default=False, verbose_name='Approved')),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('must_see', models.ManyToManyField(blank=True, to='attractions.mustsee', verbose_name='Must-see')),
            ],
        ),
    ]
