# Generated by Django 4.2 on 2024-02-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MustSee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('opening_hours', models.TextField(verbose_name='Opening hours')),
                ('min_age', models.IntegerField(verbose_name='Minimun Age')),
            ],
            options={
                'verbose_name': 'Must-see',
                'verbose_name_plural': 'Must-see',
            },
        ),
    ]
